/**
 * Textes des pages intérieures (français).
 */
export default {
  ctaBand: {
    eyebrow: 'Réservations',
    title: 'Réservez votre séjour à El Cadillar',
    lead: 'Vérifiez les disponibilités sur WhatsApp : choisissez le chalet et les dates, et nous vous répondons dans la même conversation.',
  },

  cabins: {
    eyebrow: 'Où loger à Tarija',
    title: 'Chalets à Tarija',
    lead: "Dix chalets indépendants à El Cadillar, de toutes tailles, à 7 km du centre de Tarija. Comparez la capacité, les lits et la surface, et choisissez le vôtre.",
    listTitle: 'Choisissez votre chalet',
    compare: {
      eyebrow: 'Comparer',
      title: 'Les 10 chalets côte à côte',
      caption: "Comparaison de la capacité, des lits, des salles de bain et de la surface des chalets d'El Cadillar",
      columns: {
        cabin: 'Chalet',
        guests: 'Personnes',
        beds: 'Lits',
        bathrooms: 'Salles de bain',
        area: 'Surface',
        highlight: 'Son atout',
      },
    },
    shared: {
      eyebrow: 'Sur le domaine',
      title: 'Des espaces à profiter en dehors du chalet',
      lead: "En plus de votre chalet, El Cadillar dispose d'une piscine, d'un espace barbecue, d'une terrasse, d'une cour sous pergola, de jardins et de jeux pour enfants.",
      link: "Découvrir l'expérience",
    },
  },

  cabinPage: {
    eyebrow: 'Chalet à El Cadillar · Tarija',
    factsLabel: 'Informations sur le chalet',
    aboutTitle: 'À propos du chalet',
    highlightsTitle: 'Ce qui le distingue',
    equipmentTitle: 'Caractéristiques et équipements',
    equipmentNote: 'Équipements visibles sur les photographies. Si vous avez besoin de quelque chose en particulier, demandez-nous.',
    sharedTitle: 'Également à El Cadillar',
    locationText: 'Dans la communauté de Cadillar, à 7 km du centre de Tarija, après Tomatitas.',
    bookingTitle: 'Vérifier les disponibilités',
    bookingText: 'Choisissez vos dates et nous vous répondons sur WhatsApp.',
    othersTitle: 'Autres chalets',
    othersLead: "Comparez avec les autres options d'El Cadillar.",
    previous: 'Chalet précédent',
    next: 'Chalet suivant',
    galleryLabel: 'Photos du {name}',
  },

  experience: {
    eyebrow: "L'expérience",
    title: "L'expérience El Cadillar",
    lead: "Il ne s'agit pas seulement de dormir : c'est arriver à Tarija, s'installer dans son chalet, passer l'après-midi à la piscine, partager un repas à l'espace barbecue et partir découvrir la région en sachant qu'un endroit calme vous attend au retour.",
    momentsEyebrow: 'Une journée à El Cadillar',
    momentsTitle: 'Un séjour, heure par heure',
    spacesEyebrow: 'Les espaces',
    spacesTitle: 'À profiter sans quitter le domaine',
    businessCta: 'Demander un devis sur WhatsApp',
    businessLink: 'Découvrir la salle',
  },

  tarija: {
    eyebrow: 'Sud de la Bolivie',
    title: 'Découvrir Tarija',
    lead: "Vin et singani d'altitude, cascades, villages chargés d'histoire et la Fiesta Grande, inscrite à l'UNESCO. Une région à parcourir sans se presser, avec El Cadillar comme point de départ.",
    intro: {
      eyebrow: 'Pourquoi visiter Tarija',
      title: 'Une vallée tempérée entre les collines',
      paragraphs: [
        "Tarija se situe à environ 1 850 mètres d'altitude, dans le sud de la Bolivie, avec un climat tempéré et une température moyenne de 18 °C. C'est la terre du vin bolivien et des chapacos, avec sa cuisine et ses fêtes qui remplissent les rues.",
        "Depuis El Cadillar, les rivières et les cascades de Tomatitas et Coimata sont à quelques minutes ; le village de San Lorenzo à 11 km, et les caves du Valle de la Concepción à 33 km.",
      ],
    },
    destinationsEyebrow: 'Que faire',
    destinationsTitle: 'Que faire à Tarija',
    destinationsLead: "Des lieux à découvrir, avec la distance approximative par la route depuis El Cadillar.",
    fromCadillar: "À {n} km d'El Cadillar",
    gettingEyebrow: 'Accès',
    gettingTitle: 'Comment venir à Tarija',
    base: {
      eyebrow: 'Votre base à Tarija',
      title: 'Explorez la journée, reposez-vous à El Cadillar',
      text: 'Après les caves, les cascades et les villages, retrouvez votre chalet, la piscine et le calme de la campagne.',
    },
    creditsTitle: 'Crédits photographiques',
    creditsText: 'Les photos de Tarija proviennent de Wikimedia Commons :',
    sources: 'Sources sur Tarija : Wikipédia, UNESCO, gouvernement de Tarija, presse et sites de tourisme de Tarija, consultés en septembre 2026.',
  },

  business: {
    eyebrow: "Réunions d'entreprise",
    title: 'Une salle pour vos réunions, dans le calme de Tarija',
    lead: "Réunissez votre équipe loin du bruit de la ville, avec hébergement, apéritifs et repas sur place. Vous vous occupez de la réunion ; nous, du lieu, du repos et des repas.",
    quote: 'Demander un devis sur WhatsApp',
    seeDetails: 'Voir la salle en détail',
    link: "Découvrir la salle d'entreprise",
    whyEyebrow: 'Pourquoi El Cadillar',
    whyTitle: 'Le lieu idéal pour votre prochaine réunion',
    whyLead: 'Un espace pour travailler concentrés et bien se reposer, à quelques minutes de la ville.',
    specsEyebrow: 'Fiche de la salle',
    specsTitle: 'La salle en détail',
    specsLead: 'Envoyez-nous la date et le nombre de personnes : nous confirmons la disponibilité et la façon dont nous préparons la salle pour votre réunion.',
    servicesEyebrow: 'Services',
    servicesTitle: 'Tout pour votre journée, au même endroit',
    servicesLead: "Ajoutez à la salle l'hébergement, les apéritifs et les repas, et organisez toute la réunion avec un seul interlocuteur.",
    lodgingEyebrow: 'Hébergement',
    lodgingTitle: 'Votre équipe dort sur place',
    lodgingLead: "Aucun trajet en fin de journée : 10 chalets indépendants sur le même domaine, {n} places au total, entre jardins, piscine et espace barbecue.",
    lodgingSpaces: 'Voir les espaces',
    stepsEyebrow: 'Comment obtenir un devis',
    stepsTitle: 'Votre devis en trois étapes',
    steps: [
      { title: 'Écrivez-nous sur WhatsApp', text: 'Indiquez la date, le nombre de participants et les services dont vous avez besoin.' },
      { title: 'Recevez la proposition', text: 'Nous confirmons la disponibilité et vous envoyons le devis.' },
      { title: "C'est confirmé", text: "Nous préparons la salle, l'hébergement et les repas choisis pour votre équipe." },
    ],
    ctaEyebrow: "Réunions d'entreprise",
    ctaTitle: 'Vous organisez une réunion à Tarija ?',
    ctaLead: "Envoyez-nous la date et le nombre de personnes, et nous vous répondons avec une proposition : salle, hébergement et repas.",
  },

  galleryPage: {
    eyebrow: 'Galerie',
    title: "Photos d'El Cadillar",
    lead: "Parcourez les chalets, la piscine, l'espace barbecue, la terrasse et les jardins. Toutes les photos ont été prises sur place.",
    count: { one: '{n} photo', other: '{n} photos' },
  },

  location: {
    eyebrow: 'Accès',
    title: 'Comment venir à El Cadillar',
    lead: "Dans la communauté de Cadillar, commune de San Lorenzo, à 7 km du centre de Tarija : après Tomatitas, sur la route de La Victoria et Coimata.",
    addressTitle: 'Adresse',
    coordinatesTitle: 'Coordonnées',
    distancesEyebrow: 'Distances',
    distancesTitle: 'Tout est à deux pas',
    distancesNote: "Distances approximatives par la route depuis El Cadillar.",
    groups: { llegada: 'Pour arriver', cerca: 'Sorties à proximité', excursion: 'Excursions à la journée' },
    gettingEyebrow: 'Voyager à Tarija',
    gettingTitle: "Depuis d'autres villes et pays",
  },

  contact: {
    eyebrow: 'Contact',
    title: 'Parlons de votre voyage à Tarija',
    lead: "Le plus rapide pour connaître les disponibilités, c'est WhatsApp : cela fonctionne depuis n'importe quel pays avec une connexion internet.",
    whatsappTitle: 'WhatsApp',
    whatsappText: 'Questions et réservations',
    locationTitle: 'Accès',
    socialTitle: 'Réseaux et plateformes',
    socialText: 'Suivez-nous, et retrouvez-nous aussi sur Airbnb.',
    phoneTitle: 'Téléphone',
    emailTitle: 'E-mail',
    hoursTitle: 'Horaires',
    checkIn: 'Arrivée à partir de {time}',
    checkOut: "Départ jusqu'à {time}",
    faqEyebrow: 'Questions fréquentes',
    faqTitle: 'Ce qu’il vaut mieux savoir avant de venir',
    faqMore: 'Vous ne trouvez pas votre question ? Écrivez-nous sur WhatsApp.',
  },

  booking: {
    eyebrow: 'Réservations',
    title: 'Vérifier les disponibilités',
    lead: "Choisissez le chalet, vos dates et le nombre de voyageurs. À l'envoi, WhatsApp s'ouvre avec votre demande prête à partir.",
    steps: [
      { title: 'Remplissez votre demande', text: "Dates, chalet et nombre de personnes. Si vous hésitez sur le chalet, nous vous aidons." },
      { title: 'Envoyez-la sur WhatsApp', text: "Une conversation s'ouvre avec le message prêt. Cela fonctionne depuis n'importe quel pays." },
      { title: 'Nous organisons votre séjour', text: 'Nous vous répondons dans la même conversation avec les disponibilités.' },
    ],
    form: {
      title: 'Votre demande',
      cabin: 'Chalet',
      cabinAny: 'Je ne sais pas encore, conseillez-moi',
      cabinOption: "{name} · jusqu'à {n} personnes",
      checkIn: 'Arrivée',
      checkOut: 'Départ',
      adults: 'Adultes',
      children: 'Enfants',
      name: 'Votre nom',
      origin: "D'où voyagez-vous ?",
      originPlaceholder: 'Ville et pays',
      message: 'Message (facultatif)',
      messagePlaceholder: "Motif du voyage, heure d'arrivée estimée, âge des enfants…",
      submit: 'Envoyer la demande sur WhatsApp',
      note: "Rien n'est envoyé tant que vous n'avez pas confirmé le message dans WhatsApp.",
      nights: { one: '{n} nuit', other: '{n} nuits' },
      capacityWarning: "Le {name} accueille jusqu'à {n} personnes. Choisissez un autre chalet ou demandez-nous une option.",
      dateError: "La date de départ doit être postérieure à la date d'arrivée.",
      noscript: 'Le formulaire nécessite JavaScript. Vous pouvez aussi nous écrire directement sur WhatsApp.',
    },
    message: {
      intro: 'Bonjour, je souhaiterais connaître les disponibilités pour séjourner à El Cadillar.',
      cabin: 'Chalet : {value}',
      cabinAny: 'Chalet : je souhaiterais un conseil',
      dates: 'Dates : du {checkIn} au {checkOut} ({nights})',
      arrival: 'Arrivée : {value}',
      adults: { one: '{n} adulte', other: '{n} adultes' },
      children: { one: '{n} enfant', other: '{n} enfants' },
      guests: 'Personnes : {value}',
      name: 'Nom : {value}',
      origin: 'Je voyage depuis : {value}',
      thanks: 'Merci !',
    },
    asideTitle: "Les chalets en un coup d'œil",
    directTitle: 'Vous préférez écrire directement ?',
  },

  notFound: {
    eyebrow: 'Erreur 404',
    title: 'Nous ne trouvons pas cette page',
    lead: "Le lien a peut-être changé. Voici quelques chemins pour continuer à découvrir El Cadillar.",
  },
};
