/**
 * Textes d'interface partagés par toutes les pages (français).
 */
export default {
  skip: 'Aller au contenu',
  nav: {
    home: 'Accueil',
    cabins: 'Chalets',
    experience: 'Expérience',
    business: 'Entreprises',
    tarija: 'Tarija',
    gallery: 'Galerie',
    location: 'Accès',
    contact: 'Contact',
    booking: 'Réserver',
    label: 'Navigation principale',
    language: 'Langue',
    open: 'Ouvrir le menu',
    close: 'Fermer le menu',
    breadcrumb: 'Vous êtes ici',
  },
  actions: {
    book: 'Réserver',
    checkAvailability: 'Vérifier les disponibilités',
    seeCabins: 'Découvrir les chalets',
    compareCabins: 'Comparer les 10 chalets',
    seeCabin: 'Voir le chalet',
    whatsapp: 'Écrire sur WhatsApp',
    directions: 'Itinéraire',
    openMap: 'Ouvrir dans Google Maps',
    seeAllPhotos: { one: 'Voir la photo', other: 'Voir les {n} photos' },
    seeGallery: 'Voir toute la galerie',
    backHome: "Retour à l'accueil",
    previous: 'Précédent',
    next: 'Suivant',
    close: 'Fermer',
  },
  whatsappDefault: 'Bonjour, je souhaiterais connaître les disponibilités pour séjourner à El Cadillar.',
  cabin: {
    guests: { one: '{n} personne', other: "Jusqu'à {n} personnes" },
    guestsFor: { one: "Jusqu'à {n} personne", other: "Jusqu'à {n} personnes" },
    bathrooms: { one: '{n} salle de bain', other: '{n} salles de bain' },
    area: '{n} m²',
    levels: { one: 'Un niveau', other: '{n} niveaux' },
    beds: {
      doble: { one: '{n} lit double', other: '{n} lits doubles' },
      simple: { one: '{n} lit simple', other: '{n} lits simples' },
      triple: { one: '{n} lit triple', other: '{n} lits triples' },
      'sofa-cama': { one: '{n} canapé-lit', other: '{n} canapés-lits' },
    },
    labels: { guests: 'Capacité', beds: 'Lits', bathrooms: 'Salles de bain', area: 'Surface', levels: 'Niveaux' },
    whatsappMessage: 'Bonjour, je souhaiterais connaître les disponibilités du {name} à El Cadillar.',
    filterLabel: 'Filtrer les chalets par capacité',
    filterAll: 'Tous',
    filterGuests: "Jusqu'à {n}",
  },
  gallery: {
    filterLabel: 'Filtrer les photos par espace',
    open: 'Agrandir la photo : {alt}',
  },
  lightbox: {
    label: 'Visionneuse de photos',
    counter: '{current} sur {total}',
  },
  map: {
    title: "Carte indiquant l'emplacement d'El Cadillar Apart Hotel",
    km: '{n} km',
  },
  mobileBar: {
    label: 'Réservation rapide',
    whatsapp: 'WhatsApp',
  },
  footer: {
    tagline: 'Nature et repos',
    explore: 'Explorer',
    contact: 'Contact',
    follow: 'Nous suivre',
    rights: '© {year} El Cadillar Apart Hotel. Tous droits réservés.',
    credit: 'Développé par',
    photoCredits: 'Photos de Tarija : Wikimedia Commons, sous licences Creative Commons.',
  },
};
