/**
 * Textos de las páginas interiores (español).
 */
export default {
  ctaBand: {
    eyebrow: 'Reservas',
    title: 'Reserva tu estadía en El Cadillar',
    lead: 'Consulta disponibilidad por WhatsApp: elige la cabaña y las fechas, y te respondemos por el mismo chat.',
  },

  cabins: {
    eyebrow: 'Alojamiento en Tarija',
    title: 'Cabañas en Tarija',
    lead: 'Diez cabañas independientes en El Cadillar, para 3, 4 o 5 personas, a 7 km del centro de Tarija. Compara capacidad, camas y superficie, y elige la tuya.',
    listTitle: 'Elige tu cabaña',
    compare: {
      eyebrow: 'Comparar',
      title: 'Las 10 cabañas lado a lado',
      caption: 'Comparación de capacidad, camas, baños y superficie de las cabañas de El Cadillar',
      columns: {
        cabin: 'Cabaña',
        guests: 'Personas',
        beds: 'Camas',
        bathrooms: 'Baños',
        area: 'Superficie',
        highlight: 'Destaca por',
      },
    },
    shared: {
      eyebrow: 'En el predio',
      title: 'Espacios para disfrutar fuera de la cabaña',
      lead: 'Además de tu cabaña, El Cadillar tiene piscina, quincho, terraza, patio con pérgola, jardines y juegos infantiles.',
      link: 'Conocer la experiencia',
    },
  },

  cabinPage: {
    eyebrow: 'Cabaña en El Cadillar · Tarija',
    factsLabel: 'Datos de la cabaña',
    aboutTitle: 'Sobre la cabaña',
    highlightsTitle: 'Lo que la distingue',
    equipmentTitle: 'Características y equipamiento',
    equipmentNote: 'Equipamiento visible en las fotografías. Si necesitas algo en particular, consúltanos.',
    sharedTitle: 'Además, en El Cadillar',
    locationText: 'En la comunidad de Cadillar, a 7 km del centro de Tarija, pasando Tomatitas.',
    bookingTitle: 'Consulta disponibilidad',
    bookingText: 'Elige tus fechas y te respondemos por WhatsApp.',
    othersTitle: 'Otras cabañas',
    othersLead: 'Compara con otras opciones de El Cadillar.',
    previous: 'Cabaña anterior',
    next: 'Cabaña siguiente',
    galleryLabel: 'Fotos de la {name}',
  },

  experience: {
    eyebrow: 'La experiencia',
    title: 'La experiencia El Cadillar',
    lead: 'No se trata solo de dónde dormir: es llegar a Tarija, instalarte en tu cabaña, pasar la tarde en la piscina, compartir en el quincho y salir a descubrir la región sabiendo que tienes un lugar tranquilo al que volver.',
    momentsEyebrow: 'Un día en El Cadillar',
    momentsTitle: 'Así se vive una estadía',
    spacesEyebrow: 'Los espacios',
    spacesTitle: 'Para disfrutar sin salir del predio',
    businessCta: 'Cotizar por WhatsApp',
    businessLink: 'Conocer el salón',
  },

  tarija: {
    eyebrow: 'Sur de Bolivia',
    title: 'Descubre Tarija',
    lead: 'Vino y singani de altura, cascadas, pueblos con historia y la Fiesta Grande, Patrimonio de la Humanidad. Una región para recorrer sin apuro, con El Cadillar como punto de partida.',
    intro: {
      eyebrow: 'Por qué visitar Tarija',
      title: 'Un valle templado entre cerros',
      paragraphs: [
        'Tarija está a unos 1.850 metros de altura, en el sur de Bolivia, con clima templado y una temperatura media de 18 °C. Es la tierra del vino boliviano y de los chapacos, con una cocina propia y fiestas que llenan las calles.',
        'Desde El Cadillar tienes a pocos minutos los ríos y cascadas de Tomatitas y Coimata; a 11 km, el pueblo de San Lorenzo, y a 33 km, las bodegas del Valle de la Concepción.',
      ],
    },
    destinationsEyebrow: 'Qué hacer',
    destinationsTitle: 'Qué hacer en Tarija',
    destinationsLead: 'Lugares para descubrir, con la distancia aproximada por carretera desde El Cadillar.',
    fromCadillar: 'A {n} km de El Cadillar',
    gettingEyebrow: 'Cómo llegar',
    gettingTitle: 'Cómo llegar a Tarija',
    base: {
      eyebrow: 'Tu base en Tarija',
      title: 'Explora de día, descansa en El Cadillar',
      text: 'Después de recorrer bodegas, cascadas y pueblos, vuelve a tu cabaña, a la piscina y a la calma del campo.',
    },
    creditsTitle: 'Créditos de las fotografías',
    creditsText: 'Las fotos de Tarija provienen de Wikimedia Commons:',
    sources: 'Datos de Tarija: Wikipedia, UNESCO, Gobernación de Tarija, prensa y sitios de turismo de Tarija, consultados en septiembre de 2026.',
  },

  business: {
    eyebrow: 'Reuniones empresariales',
    title: 'Un salón para reuniones de trabajo, en la calma de Tarija',
    lead: 'Reúne a tu equipo lejos del ruido de la ciudad, con hospedaje, aperitivos y comidas en el mismo lugar. Tú te ocupas de la reunión; nosotros, del lugar, el descanso y la comida.',
    quote: 'Cotizar por WhatsApp',
    seeDetails: 'Ver el salón en detalle',
    link: 'Conocer el salón empresarial',
    whyEyebrow: 'Por qué El Cadillar',
    whyTitle: 'El lugar ideal para tu próxima reunión',
    whyLead: 'Un espacio para trabajar concentrados y descansar bien, a pocos minutos de la ciudad.',
    specsEyebrow: 'Ficha del salón',
    specsTitle: 'El salón en detalle',
    specsLead: 'Escríbenos con la fecha y la cantidad de personas, y te confirmamos la disponibilidad y cómo preparamos el salón para tu reunión.',
    servicesEyebrow: 'Servicios',
    servicesTitle: 'Todo para tu jornada, en un solo lugar',
    servicesLead: 'Suma al salón el hospedaje, los aperitivos y las comidas, y organiza la reunión completa con un solo contacto.',
    lodgingEyebrow: 'Hospedaje',
    lodgingTitle: 'Tu equipo, alojado en el mismo lugar',
    lodgingLead: 'Sin traslados al final del día: 10 cabañas independientes en el mismo predio, con {n} plazas en total, entre jardines, piscina y quincho.',
    lodgingSpaces: 'Ver los espacios',
    stepsEyebrow: 'Cómo cotizar',
    stepsTitle: 'Tu cotización en tres pasos',
    steps: [
      { title: 'Escríbenos por WhatsApp', text: 'Cuéntanos la fecha, cuántas personas participan y qué servicios necesitas.' },
      { title: 'Recibe la propuesta', text: 'Te confirmamos la disponibilidad y te enviamos la cotización.' },
      { title: 'Confirma y listo', text: 'Preparamos el salón, el hospedaje y las comidas que elegiste para tu equipo.' },
    ],
    ctaEyebrow: 'Reuniones empresariales',
    ctaTitle: '¿Organizas una reunión en Tarija?',
    ctaLead: 'Escríbenos con la fecha y la cantidad de personas, y te enviamos una propuesta con el salón, el hospedaje y las comidas.',
  },

  galleryPage: {
    eyebrow: 'Galería',
    title: 'Fotos de El Cadillar',
    lead: 'Recorre las cabañas, la piscina, el quincho, la terraza y los jardines. Todas las fotos son del lugar.',
    count: { one: '{n} foto', other: '{n} fotos' },
  },

  location: {
    eyebrow: 'Ubicación',
    title: 'Cómo llegar a El Cadillar',
    lead: 'En la comunidad de Cadillar, municipio de San Lorenzo, a 7 km del centro de Tarija: pasando Tomatitas, sobre el camino a La Victoria y Coimata.',
    addressTitle: 'Dirección',
    coordinatesTitle: 'Coordenadas',
    distancesEyebrow: 'Distancias',
    distancesTitle: 'Qué tan cerca está todo',
    distancesNote: 'Distancias aproximadas por carretera desde El Cadillar.',
    groups: { llegada: 'Para llegar', cerca: 'Paseos cercanos', excursion: 'Excursiones de día' },
    gettingEyebrow: 'Viajar a Tarija',
    gettingTitle: 'Desde otras ciudades y países',
  },

  contact: {
    eyebrow: 'Contacto',
    title: 'Hablemos de tu viaje a Tarija',
    lead: 'La forma más rápida de consultar disponibilidad es WhatsApp: funciona desde cualquier país con conexión a internet.',
    whatsappTitle: 'WhatsApp',
    whatsappText: 'Consultas y reservas',
    locationTitle: 'Ubicación',
    socialTitle: 'Redes y plataformas',
    socialText: 'Síguenos y encuéntranos también en Airbnb.',
    phoneTitle: 'Teléfono',
    emailTitle: 'Correo electrónico',
    hoursTitle: 'Horarios',
    checkIn: 'Check-in desde las {time}',
    checkOut: 'Check-out hasta las {time}',
    faqEyebrow: 'Preguntas frecuentes',
    faqTitle: 'Lo que conviene saber antes de venir',
    faqMore: '¿No encuentras tu pregunta? Escríbenos por WhatsApp.',
  },

  booking: {
    eyebrow: 'Reservas',
    title: 'Consulta disponibilidad',
    lead: 'Elige la cabaña, tus fechas y cuántas personas viajan. Al enviar, se abre WhatsApp con tu consulta lista para mandar.',
    steps: [
      { title: 'Completa tu consulta', text: 'Fechas, cabaña y cantidad de personas. Si no sabes qué cabaña elegir, te ayudamos.' },
      { title: 'Envíala por WhatsApp', text: 'Se abre una conversación con el mensaje listo. Funciona desde cualquier país.' },
      { title: 'Coordinamos tu estadía', text: 'Te respondemos por el mismo chat con la disponibilidad.' },
    ],
    form: {
      title: 'Tu consulta',
      cabin: 'Cabaña',
      cabinAny: 'Aún no sé, recomiéndenme una',
      cabinOption: '{name} · hasta {n} personas',
      checkIn: 'Llegada',
      checkOut: 'Salida',
      adults: 'Adultos',
      children: 'Niños',
      name: 'Tu nombre',
      origin: '¿Desde dónde viajas?',
      originPlaceholder: 'Ciudad y país',
      message: 'Mensaje (opcional)',
      messagePlaceholder: 'Motivo del viaje, hora estimada de llegada, edades de los niños…',
      submit: 'Enviar consulta por WhatsApp',
      note: 'No se envía nada hasta que confirmes el mensaje en WhatsApp.',
      nights: { one: '{n} noche', other: '{n} noches' },
      capacityWarning: 'La {name} es para hasta {n} personas. Elige otra cabaña o consúltanos por una opción.',
      dateError: 'La fecha de salida debe ser posterior a la de llegada.',
      noscript: 'Para usar el formulario se necesita JavaScript. También puedes escribirnos directamente por WhatsApp.',
    },
    message: {
      intro: 'Hola, quisiera consultar disponibilidad para hospedarme en El Cadillar.',
      cabin: 'Cabaña: {value}',
      cabinAny: 'Cabaña: me gustaría una recomendación',
      dates: 'Fechas: del {checkIn} al {checkOut} ({nights})',
      arrival: 'Llegada: {value}',
      adults: { one: '{n} adulto', other: '{n} adultos' },
      children: { one: '{n} niño', other: '{n} niños' },
      guests: 'Personas: {value}',
      name: 'Nombre: {value}',
      origin: 'Viajo desde: {value}',
      thanks: '¡Gracias!',
    },
    asideTitle: 'Las cabañas de un vistazo',
    directTitle: '¿Prefieres escribir directamente?',
  },

  notFound: {
    eyebrow: 'Error 404',
    title: 'No encontramos esta página',
    lead: 'Puede que el enlace haya cambiado. Te dejamos algunos caminos para seguir recorriendo El Cadillar.',
  },
};
