/**
 * Textos de interfaz compartidos por todas las páginas (español).
 */
export default {
  skip: 'Saltar al contenido',
  nav: {
    home: 'Inicio',
    cabins: 'Cabañas',
    experience: 'Experiencia',
    business: 'Empresas',
    tarija: 'Tarija',
    gallery: 'Galería',
    location: 'Ubicación',
    contact: 'Contacto',
    booking: 'Reservar',
    label: 'Navegación principal',
    open: 'Abrir menú',
    close: 'Cerrar menú',
    breadcrumb: 'Estás en',
  },
  actions: {
    book: 'Reservar',
    checkAvailability: 'Consultar disponibilidad',
    seeCabins: 'Conocer las cabañas',
    compareCabins: 'Comparar las 10 cabañas',
    seeCabin: 'Ver cabaña',
    whatsapp: 'Escribir por WhatsApp',
    directions: 'Cómo llegar',
    openMap: 'Abrir en Google Maps',
    seeAllPhotos: { one: 'Ver la foto', other: 'Ver las {n} fotos' },
    seeGallery: 'Ver la galería completa',
    backHome: 'Volver al inicio',
    previous: 'Anterior',
    next: 'Siguiente',
    close: 'Cerrar',
  },
  whatsappDefault: 'Hola, quisiera consultar disponibilidad para hospedarme en El Cadillar.',
  cabin: {
    guests: { one: '{n} persona', other: 'Hasta {n} personas' },
    guestsFor: { one: 'Para {n} persona', other: 'Para {n} personas' },
    bathrooms: { one: '{n} baño', other: '{n} baños' },
    area: '{n} m²',
    levels: { one: 'Una planta', other: '{n} plantas' },
    beds: {
      doble: { one: '{n} cama doble', other: '{n} camas dobles' },
      simple: { one: '{n} cama simple', other: '{n} camas simples' },
      triple: { one: '{n} cama triple', other: '{n} camas triples' },
      'sofa-cama': { one: '{n} sofá cama', other: '{n} sofás cama' },
    },
    labels: { guests: 'Capacidad', beds: 'Camas', bathrooms: 'Baños', area: 'Superficie', levels: 'Plantas' },
    whatsappMessage: 'Hola, quisiera consultar disponibilidad de la {name} en El Cadillar.',
    filterLabel: 'Filtrar cabañas por capacidad',
    filterAll: 'Todas',
    filterGuests: 'Para {n}',
  },
  gallery: {
    filterLabel: 'Filtrar fotos por espacio',
    open: 'Ampliar foto: {alt}',
  },
  lightbox: {
    label: 'Visor de fotos',
    counter: '{current} de {total}',
  },
  map: {
    title: 'Mapa con la ubicación de El Cadillar Apart Hotel',
    km: '{n} km',
  },
  mobileBar: {
    label: 'Reserva rápida',
    whatsapp: 'WhatsApp',
  },
  footer: {
    tagline: 'Naturaleza y descanso',
    explore: 'Explorar',
    contact: 'Contacto',
    follow: 'Síguenos',
    rights: '© {year} El Cadillar Apart Hotel. Todos los derechos reservados.',
    credit: 'Desarrollado por',
    photoCredits: 'Fotos de Tarija: Wikimedia Commons, con licencias Creative Commons.',
  },
};
