/**
 * Texts for the inner pages (English).
 */
export default {
  ctaBand: {
    eyebrow: 'Bookings',
    title: 'Book your stay at El Cadillar',
    lead: 'Check availability on WhatsApp: choose your cabin and dates, and we will answer in the same chat.',
  },

  cabins: {
    eyebrow: 'Where to stay in Tarija',
    title: 'Cabins in Tarija',
    lead: 'Ten independent cabins at El Cadillar, for 1 to 5 guests, 7 km from the centre of Tarija. Compare capacity, beds and size, and choose yours.',
    listTitle: 'Choose your cabin',
    compare: {
      eyebrow: 'Compare',
      title: 'All 10 cabins side by side',
      caption: 'Comparison of capacity, beds, bathrooms and size of the cabins at El Cadillar',
      columns: {
        cabin: 'Cabin',
        guests: 'Guests',
        beds: 'Beds',
        bathrooms: 'Bathrooms',
        area: 'Size',
        highlight: 'Known for',
      },
    },
    shared: {
      eyebrow: 'On the grounds',
      title: 'Places to enjoy outside your cabin',
      lead: 'Beyond your cabin, El Cadillar has a pool, a barbecue house, a terrace, a pergola courtyard, gardens and a playground.',
      link: 'See the experience',
    },
  },

  cabinPage: {
    eyebrow: 'Cabin at El Cadillar · Tarija',
    factsLabel: 'Cabin details',
    aboutTitle: 'About this cabin',
    highlightsTitle: 'What makes it special',
    equipmentTitle: 'Features and equipment',
    equipmentNote: 'Equipment visible in the photographs. If you need anything in particular, just ask.',
    sharedTitle: 'Also at El Cadillar',
    locationText: 'In the community of Cadillar, 7 km from the centre of Tarija, just past Tomatitas.',
    bookingTitle: 'Check availability',
    bookingText: 'Choose your dates and we will reply on WhatsApp.',
    othersTitle: 'Other cabins',
    othersLead: 'Compare with the other options at El Cadillar.',
    previous: 'Previous cabin',
    next: 'Next cabin',
    galleryLabel: 'Photos of {name}',
  },

  experience: {
    eyebrow: 'The experience',
    title: 'The El Cadillar experience',
    lead: 'It is not only about where you sleep: it is arriving in Tarija, settling into your cabin, spending the afternoon by the pool, sharing a meal at the barbecue house and heading out to discover the region knowing you have a quiet place to come back to.',
    momentsEyebrow: 'A day at El Cadillar',
    momentsTitle: 'What a stay feels like',
    spacesEyebrow: 'The spaces',
    spacesTitle: 'To enjoy without leaving the grounds',
    businessCta: 'Get a quote on WhatsApp',
    businessLink: 'See the meeting room',
  },

  tarija: {
    eyebrow: 'Southern Bolivia',
    title: 'Discover Tarija',
    lead: 'High-altitude wine and singani, waterfalls, towns with history and the Fiesta Grande, recognised by UNESCO. A region to explore slowly, with El Cadillar as your base.',
    intro: {
      eyebrow: 'Why visit Tarija',
      title: 'A mild valley among the hills',
      paragraphs: [
        'Tarija sits at around 1,850 metres in southern Bolivia, with a mild climate and an average temperature of 18 °C. This is the land of Bolivian wine and of the chapacos, with a cuisine of its own and festivals that fill the streets.',
        'From El Cadillar, the rivers and waterfalls of Tomatitas and Coimata are minutes away; the town of San Lorenzo is 11 km away, and the wineries of Valle de la Concepción, 33 km.',
      ],
    },
    destinationsEyebrow: 'What to do',
    destinationsTitle: 'What to do in Tarija',
    destinationsLead: 'Places worth discovering, with the approximate driving distance from El Cadillar.',
    fromCadillar: '{n} km from El Cadillar',
    gettingEyebrow: 'Getting there',
    gettingTitle: 'How to get to Tarija',
    base: {
      eyebrow: 'Your base in Tarija',
      title: 'Explore by day, rest at El Cadillar',
      text: 'After a day of wineries, waterfalls and villages, come back to your cabin, the pool and the quiet of the countryside.',
    },
    creditsTitle: 'Photo credits',
    creditsText: 'The photos of Tarija come from Wikimedia Commons:',
    sources: 'Sources on Tarija: Wikipedia, UNESCO, the Government of Tarija, press and Tarija tourism sites, consulted in September 2026.',
  },

  business: {
    eyebrow: 'Company meetings',
    title: 'A room for work meetings, in the calm of Tarija',
    lead: 'Bring your team together away from the noise of the city, with lodging, refreshments and meals in the same place. You take care of the meeting; we take care of the room, the rest and the food.',
    quote: 'Get a quote on WhatsApp',
    seeDetails: 'See the room in detail',
    link: 'See the meeting room',
    whyEyebrow: 'Why El Cadillar',
    whyTitle: 'The right place for your next meeting',
    whyLead: 'A space to work with focus and rest well, minutes from the city.',
    specsEyebrow: 'Room details',
    specsTitle: 'The room in detail',
    specsLead: 'Send us the date and the number of people, and we will confirm availability and how we set the room up for your meeting.',
    servicesEyebrow: 'Services',
    servicesTitle: 'Everything for your day, in one place',
    servicesLead: 'Add lodging, refreshments and meals to the room, and organise the whole meeting through a single contact.',
    lodgingEyebrow: 'Lodging',
    lodgingTitle: 'Your team stays right here',
    lodgingLead: 'No travelling at the end of the day: 10 independent cabins on the same grounds, sleeping {n} people in total, among gardens, pool and barbecue house.',
    lodgingSpaces: 'See the spaces',
    stepsEyebrow: 'How to get a quote',
    stepsTitle: 'Your quote in three steps',
    steps: [
      { title: 'Message us on WhatsApp', text: 'Tell us the date, how many people are taking part and which services you need.' },
      { title: 'Receive the proposal', text: 'We confirm availability and send you the quote.' },
      { title: 'Confirm and that is it', text: 'We prepare the room, the lodging and the meals you chose for your team.' },
    ],
    ctaEyebrow: 'Company meetings',
    ctaTitle: 'Planning a meeting in Tarija?',
    ctaLead: 'Send us the date and the number of people, and we will reply with a proposal covering the room, the lodging and the meals.',
  },

  galleryPage: {
    eyebrow: 'Gallery',
    title: 'Photos of El Cadillar',
    lead: 'Walk through the cabins, the pool, the barbecue house, the terrace and the gardens. Every photo was taken here.',
    count: { one: '{n} photo', other: '{n} photos' },
  },

  location: {
    eyebrow: 'Location',
    title: 'How to get to El Cadillar',
    lead: 'In the community of Cadillar, municipality of San Lorenzo, 7 km from the centre of Tarija: past Tomatitas, on the road to La Victoria and Coimata.',
    addressTitle: 'Address',
    coordinatesTitle: 'Coordinates',
    distancesEyebrow: 'Distances',
    distancesTitle: 'How close everything is',
    distancesNote: 'Approximate driving distances from El Cadillar.',
    groups: { llegada: 'Arriving', cerca: 'Nearby outings', excursion: 'Day trips' },
    gettingEyebrow: 'Travelling to Tarija',
    gettingTitle: 'From other cities and countries',
  },

  contact: {
    eyebrow: 'Contact',
    title: 'Let us talk about your trip to Tarija',
    lead: 'The fastest way to check availability is WhatsApp: it works from any country with an internet connection.',
    whatsappTitle: 'WhatsApp',
    whatsappText: 'Enquiries and bookings',
    locationTitle: 'Location',
    socialTitle: 'Social media and platforms',
    socialText: 'Follow us, and find us on Airbnb as well.',
    phoneTitle: 'Phone',
    emailTitle: 'Email',
    hoursTitle: 'Times',
    checkIn: 'Check-in from {time}',
    checkOut: 'Check-out until {time}',
    faqEyebrow: 'Frequently asked questions',
    faqTitle: 'What is worth knowing before you come',
    faqMore: 'Cannot find your question? Message us on WhatsApp.',
  },

  booking: {
    eyebrow: 'Bookings',
    title: 'Check availability',
    lead: 'Choose the cabin, your dates and how many people are travelling. When you send it, WhatsApp opens with your enquiry ready to go.',
    steps: [
      { title: 'Fill in your enquiry', text: 'Dates, cabin and number of guests. If you are not sure which cabin to choose, we will help.' },
      { title: 'Send it on WhatsApp', text: 'A chat opens with the message ready. It works from any country.' },
      { title: 'We arrange your stay', text: 'We reply in the same chat with availability.' },
    ],
    form: {
      title: 'Your enquiry',
      cabin: 'Cabin',
      cabinAny: 'Not sure yet, please recommend one',
      cabinOption: '{name} · up to {n} guests',
      checkIn: 'Arrival',
      checkOut: 'Departure',
      adults: 'Adults',
      children: 'Children',
      name: 'Your name',
      origin: 'Where are you travelling from?',
      originPlaceholder: 'City and country',
      message: 'Message (optional)',
      messagePlaceholder: 'Reason for the trip, estimated arrival time, ages of the children…',
      submit: 'Send enquiry on WhatsApp',
      note: 'Nothing is sent until you confirm the message in WhatsApp.',
      nights: { one: '{n} night', other: '{n} nights' },
      capacityWarning: '{name} sleeps up to {n} guests. Choose another cabin or ask us for an option.',
      dateError: 'The departure date must be after the arrival date.',
      noscript: 'The form needs JavaScript. You can also write to us directly on WhatsApp.',
    },
    message: {
      intro: 'Hello! I would like to check availability at El Cadillar.',
      cabin: 'Cabin: {value}',
      cabinAny: 'Cabin: I would like a recommendation',
      dates: 'Dates: {checkIn} to {checkOut} ({nights})',
      arrival: 'Arrival: {value}',
      adults: { one: '{n} adult', other: '{n} adults' },
      children: { one: '{n} child', other: '{n} children' },
      guests: 'Guests: {value}',
      name: 'Name: {value}',
      origin: 'Travelling from: {value}',
      thanks: 'Thank you!',
    },
    asideTitle: 'The cabins at a glance',
    directTitle: 'Prefer to write directly?',
  },

  notFound: {
    eyebrow: 'Error 404',
    title: 'We could not find this page',
    lead: 'The link may have changed. Here are a few ways to keep exploring El Cadillar.',
  },
};
