/**
 * Shared interface texts for every page (English).
 */
export default {
  skip: 'Skip to content',
  nav: {
    home: 'Home',
    cabins: 'Cabins',
    experience: 'Experience',
    business: 'Meetings',
    tarija: 'Tarija',
    gallery: 'Gallery',
    location: 'Location',
    contact: 'Contact',
    booking: 'Book',
    label: 'Main navigation',
    language: 'Language',
    open: 'Open menu',
    close: 'Close menu',
    breadcrumb: 'You are here',
  },
  actions: {
    book: 'Book',
    checkAvailability: 'Check availability',
    seeCabins: 'See the cabins',
    compareCabins: 'Compare all 10 cabins',
    seeCabin: 'View cabin',
    whatsapp: 'Message us on WhatsApp',
    directions: 'Get directions',
    openMap: 'Open in Google Maps',
    seeAllPhotos: { one: 'View the photo', other: 'View all {n} photos' },
    seeGallery: 'See the full gallery',
    backHome: 'Back to home',
    previous: 'Previous',
    next: 'Next',
    close: 'Close',
  },
  whatsappDefault: 'Hello! I would like to check availability at El Cadillar.',
  cabin: {
    guests: { one: '{n} guest', other: 'Up to {n} guests' },
    guestsFor: { one: 'Up to {n} guest', other: 'Up to {n} guests' },
    bathrooms: { one: '{n} bathroom', other: '{n} bathrooms' },
    area: '{n} m²',
    levels: { one: 'One floor', other: '{n} floors' },
    beds: {
      doble: { one: '{n} double bed', other: '{n} double beds' },
      simple: { one: '{n} single bed', other: '{n} single beds' },
      triple: { one: '{n} triple bed', other: '{n} triple beds' },
      'sofa-cama': { one: '{n} sofa bed', other: '{n} sofa beds' },
    },
    labels: { guests: 'Sleeps', beds: 'Beds', bathrooms: 'Bathrooms', area: 'Size', levels: 'Floors' },
    whatsappMessage: 'Hello! I would like to check availability for {name} at El Cadillar.',
    filterLabel: 'Filter cabins by capacity',
    filterAll: 'All',
    filterGuests: 'Up to {n}',
  },
  gallery: {
    filterLabel: 'Filter photos by area',
    open: 'Enlarge photo: {alt}',
  },
  lightbox: {
    label: 'Photo viewer',
    counter: '{current} of {total}',
  },
  map: {
    title: 'Map showing where El Cadillar Apart Hotel is',
    km: '{n} km',
  },
  mobileBar: {
    label: 'Quick booking',
    whatsapp: 'WhatsApp',
  },
  footer: {
    tagline: 'Nature and rest',
    explore: 'Explore',
    contact: 'Contact',
    follow: 'Follow us',
    rights: '© {year} El Cadillar Apart Hotel. All rights reserved.',
    credit: 'Built by',
    photoCredits: 'Photos of Tarija: Wikimedia Commons, under Creative Commons licences.',
  },
};
