/**
 * Textos das páginas internas (português).
 */
export default {
  ctaBand: {
    eyebrow: 'Reservas',
    title: 'Reserve sua estadia no El Cadillar',
    lead: 'Consulte a disponibilidade pelo WhatsApp: escolha a cabana e as datas, e respondemos na mesma conversa.',
  },

  cabins: {
    eyebrow: 'Onde ficar em Tarija',
    title: 'Cabanas em Tarija',
    lead: 'Dez cabanas independentes no El Cadillar, de todos os tamanhos, a 7 km do centro de Tarija. Compare capacidade, camas e área, e escolha a sua.',
    listTitle: 'Escolha sua cabana',
    compare: {
      eyebrow: 'Comparar',
      title: 'As 10 cabanas lado a lado',
      caption: 'Comparação de capacidade, camas, banheiros e área das cabanas do El Cadillar',
      columns: {
        cabin: 'Cabana',
        guests: 'Pessoas',
        beds: 'Camas',
        bathrooms: 'Banheiros',
        area: 'Área',
        highlight: 'Destaque',
      },
    },
    shared: {
      eyebrow: 'No terreno',
      title: 'Espaços para aproveitar fora da cabana',
      lead: 'Além da sua cabana, o El Cadillar tem piscina, área de churrasco, terraço, pátio com pérgola, jardins e parquinho.',
      link: 'Conhecer a experiência',
    },
  },

  cabinPage: {
    eyebrow: 'Cabana no El Cadillar · Tarija',
    factsLabel: 'Dados da cabana',
    aboutTitle: 'Sobre a cabana',
    highlightsTitle: 'O que a torna especial',
    equipmentTitle: 'Características e equipamentos',
    equipmentNote: 'Equipamentos visíveis nas fotografias. Se precisar de algo específico, é só perguntar.',
    sharedTitle: 'Também no El Cadillar',
    locationText: 'Na comunidade de Cadillar, a 7 km do centro de Tarija, passando Tomatitas.',
    bookingTitle: 'Consultar disponibilidade',
    bookingText: 'Escolha suas datas e respondemos pelo WhatsApp.',
    othersTitle: 'Outras cabanas',
    othersLead: 'Compare com as outras opções do El Cadillar.',
    previous: 'Cabana anterior',
    next: 'Próxima cabana',
    galleryLabel: 'Fotos da {name}',
  },

  experience: {
    eyebrow: 'A experiência',
    title: 'A experiência El Cadillar',
    lead: 'Não é só onde dormir: é chegar em Tarija, se instalar na sua cabana, passar a tarde na piscina, dividir uma refeição na área de churrasco e sair para descobrir a região sabendo que há um lugar tranquilo para voltar.',
    momentsEyebrow: 'Um dia no El Cadillar',
    momentsTitle: 'Como é uma estadia',
    spacesEyebrow: 'Os espaços',
    spacesTitle: 'Para aproveitar sem sair do terreno',
    businessCta: 'Orçar pelo WhatsApp',
    businessLink: 'Conhecer a sala',
  },

  tarija: {
    eyebrow: 'Sul da Bolívia',
    title: 'Descubra Tarija',
    lead: 'Vinho e singani de altitude, cachoeiras, vilarejos com história e a Fiesta Grande, Patrimônio da Humanidade. Uma região para percorrer sem pressa, com o El Cadillar como ponto de partida.',
    intro: {
      eyebrow: 'Por que visitar Tarija',
      title: 'Um vale de clima ameno entre morros',
      paragraphs: [
        'Tarija fica a cerca de 1.850 metros de altitude, no sul da Bolívia, com clima ameno e temperatura média de 18 °C. É a terra do vinho boliviano e dos chapacos, com cozinha própria e festas que tomam as ruas.',
        'Do El Cadillar, os rios e as cachoeiras de Tomatitas e Coimata ficam a poucos minutos; o vilarejo de San Lorenzo, a 11 km, e as vinícolas do Valle de la Concepción, a 33 km.',
      ],
    },
    destinationsEyebrow: 'O que fazer',
    destinationsTitle: 'O que fazer em Tarija',
    destinationsLead: 'Lugares para descobrir, com a distância aproximada por estrada desde o El Cadillar.',
    fromCadillar: 'A {n} km do El Cadillar',
    gettingEyebrow: 'Como chegar',
    gettingTitle: 'Como chegar a Tarija',
    base: {
      eyebrow: 'Sua base em Tarija',
      title: 'Explore de dia, descanse no El Cadillar',
      text: 'Depois de percorrer vinícolas, cachoeiras e vilarejos, volte para sua cabana, para a piscina e para a calma do campo.',
    },
    creditsTitle: 'Créditos das fotografias',
    creditsText: 'As fotos de Tarija vêm do Wikimedia Commons:',
    sources: 'Fontes sobre Tarija: Wikipédia, UNESCO, Governo de Tarija, imprensa e sites de turismo de Tarija, consultados em setembro de 2026.',
  },

  business: {
    eyebrow: 'Reuniões de empresas',
    title: 'Uma sala para reuniões de trabalho, na calma de Tarija',
    lead: 'Reúna sua equipe longe do barulho da cidade, com hospedagem, aperitivos e refeições no mesmo lugar. Você cuida da reunião; nós, do espaço, do descanso e da comida.',
    quote: 'Orçar pelo WhatsApp',
    seeDetails: 'Ver a sala em detalhe',
    link: 'Conhecer a sala para empresas',
    whyEyebrow: 'Por que o El Cadillar',
    whyTitle: 'O lugar ideal para sua próxima reunião',
    whyLead: 'Um espaço para trabalhar concentrados e descansar bem, a poucos minutos da cidade.',
    specsEyebrow: 'Ficha da sala',
    specsTitle: 'A sala em detalhe',
    specsLead: 'Mande a data e a quantidade de pessoas, e confirmamos a disponibilidade e como preparamos a sala para a sua reunião.',
    servicesEyebrow: 'Serviços',
    servicesTitle: 'Tudo para o seu dia, em um só lugar',
    servicesLead: 'Some à sala a hospedagem, os aperitivos e as refeições, e organize a reunião inteira com um único contato.',
    lodgingEyebrow: 'Hospedagem',
    lodgingTitle: 'Sua equipe fica no mesmo lugar',
    lodgingLead: 'Sem deslocamentos no fim do dia: 10 cabanas independentes no mesmo terreno, com {n} vagas no total, entre jardins, piscina e área de churrasco.',
    lodgingSpaces: 'Ver os espaços',
    stepsEyebrow: 'Como orçar',
    stepsTitle: 'Seu orçamento em três passos',
    steps: [
      { title: 'Fale pelo WhatsApp', text: 'Conte a data, quantas pessoas participam e de quais serviços você precisa.' },
      { title: 'Receba a proposta', text: 'Confirmamos a disponibilidade e enviamos o orçamento.' },
      { title: 'Confirme e pronto', text: 'Preparamos a sala, a hospedagem e as refeições que você escolheu para a equipe.' },
    ],
    ctaEyebrow: 'Reuniões de empresas',
    ctaTitle: 'Vai organizar uma reunião em Tarija?',
    ctaLead: 'Mande a data e a quantidade de pessoas, e respondemos com uma proposta com a sala, a hospedagem e as refeições.',
  },

  galleryPage: {
    eyebrow: 'Galeria',
    title: 'Fotos do El Cadillar',
    lead: 'Percorra as cabanas, a piscina, a área de churrasco, o terraço e os jardins. Todas as fotos são do lugar.',
    count: { one: '{n} foto', other: '{n} fotos' },
  },

  location: {
    eyebrow: 'Como chegar',
    title: 'Como chegar ao El Cadillar',
    lead: 'Na comunidade de Cadillar, município de San Lorenzo, a 7 km do centro de Tarija: passando Tomatitas, na estrada para La Victoria e Coimata.',
    addressTitle: 'Endereço',
    coordinatesTitle: 'Coordenadas',
    distancesEyebrow: 'Distâncias',
    distancesTitle: 'Como tudo fica perto',
    distancesNote: 'Distâncias aproximadas por estrada desde o El Cadillar.',
    groups: { llegada: 'Para chegar', cerca: 'Passeios por perto', excursion: 'Passeios de um dia' },
    gettingEyebrow: 'Viajar para Tarija',
    gettingTitle: 'De outras cidades e países',
  },

  contact: {
    eyebrow: 'Contato',
    title: 'Vamos falar da sua viagem a Tarija',
    lead: 'O jeito mais rápido de consultar a disponibilidade é o WhatsApp: funciona de qualquer país com conexão à internet.',
    whatsappTitle: 'WhatsApp',
    whatsappText: 'Dúvidas e reservas',
    locationTitle: 'Localização',
    socialTitle: 'Redes e plataformas',
    socialText: 'Siga a gente e nos encontre também no Airbnb.',
    phoneTitle: 'Telefone',
    emailTitle: 'E-mail',
    hoursTitle: 'Horários',
    checkIn: 'Check-in a partir das {time}',
    checkOut: 'Check-out até as {time}',
    faqEyebrow: 'Dúvidas frequentes',
    faqTitle: 'O que vale saber antes de vir',
    faqMore: 'Não encontrou sua dúvida? Fale pelo WhatsApp.',
  },

  booking: {
    eyebrow: 'Reservas',
    title: 'Consultar disponibilidade',
    lead: 'Escolha a cabana, suas datas e quantas pessoas viajam. Ao enviar, o WhatsApp abre com sua consulta pronta.',
    steps: [
      { title: 'Preencha sua consulta', text: 'Datas, cabana e quantidade de pessoas. Se não souber qual cabana escolher, a gente ajuda.' },
      { title: 'Envie pelo WhatsApp', text: 'Abre uma conversa com a mensagem pronta. Funciona de qualquer país.' },
      { title: 'Combinamos sua estadia', text: 'Respondemos na mesma conversa com a disponibilidade.' },
    ],
    form: {
      title: 'Sua consulta',
      cabin: 'Cabana',
      cabinAny: 'Ainda não sei, me recomendem uma',
      cabinOption: '{name} · até {n} pessoas',
      checkIn: 'Chegada',
      checkOut: 'Saída',
      adults: 'Adultos',
      children: 'Crianças',
      name: 'Seu nome',
      origin: 'De onde você viaja?',
      originPlaceholder: 'Cidade e país',
      message: 'Mensagem (opcional)',
      messagePlaceholder: 'Motivo da viagem, horário estimado de chegada, idade das crianças…',
      submit: 'Enviar consulta pelo WhatsApp',
      note: 'Nada é enviado até você confirmar a mensagem no WhatsApp.',
      nights: { one: '{n} noite', other: '{n} noites' },
      capacityWarning: 'A {name} é para até {n} pessoas. Escolha outra cabana ou pergunte por uma opção.',
      dateError: 'A data de saída precisa ser posterior à de chegada.',
      noscript: 'O formulário precisa de JavaScript. Você também pode falar direto pelo WhatsApp.',
    },
    message: {
      intro: 'Olá! Gostaria de consultar a disponibilidade para me hospedar no El Cadillar.',
      cabin: 'Cabana: {value}',
      cabinAny: 'Cabana: gostaria de uma recomendação',
      dates: 'Datas: de {checkIn} a {checkOut} ({nights})',
      arrival: 'Chegada: {value}',
      adults: { one: '{n} adulto', other: '{n} adultos' },
      children: { one: '{n} criança', other: '{n} crianças' },
      guests: 'Pessoas: {value}',
      name: 'Nome: {value}',
      origin: 'Viajo de: {value}',
      thanks: 'Obrigado!',
    },
    asideTitle: 'As cabanas em um olhar',
    directTitle: 'Prefere falar direto?',
  },

  notFound: {
    eyebrow: 'Erro 404',
    title: 'Não encontramos esta página',
    lead: 'O link pode ter mudado. Aqui vão alguns caminhos para continuar conhecendo o El Cadillar.',
  },
};
