/**
 * Textos de interface compartilhados por todas as páginas (português).
 */
export default {
  skip: 'Ir para o conteúdo',
  nav: {
    home: 'Início',
    cabins: 'Cabanas',
    experience: 'Experiência',
    business: 'Empresas',
    tarija: 'Tarija',
    gallery: 'Galeria',
    location: 'Como chegar',
    contact: 'Contato',
    booking: 'Reservar',
    label: 'Navegação principal',
    language: 'Idioma',
    open: 'Abrir menu',
    close: 'Fechar menu',
    breadcrumb: 'Você está em',
  },
  actions: {
    book: 'Reservar',
    checkAvailability: 'Consultar disponibilidade',
    seeCabins: 'Conhecer as cabanas',
    compareCabins: 'Comparar as 10 cabanas',
    seeCabin: 'Ver cabana',
    whatsapp: 'Falar pelo WhatsApp',
    directions: 'Como chegar',
    openMap: 'Abrir no Google Maps',
    seeAllPhotos: { one: 'Ver a foto', other: 'Ver as {n} fotos' },
    seeGallery: 'Ver a galeria completa',
    backHome: 'Voltar ao início',
    previous: 'Anterior',
    next: 'Próxima',
    close: 'Fechar',
  },
  whatsappDefault: 'Olá! Gostaria de consultar a disponibilidade para me hospedar no El Cadillar.',
  cabin: {
    guests: { one: '{n} pessoa', other: 'Até {n} pessoas' },
    guestsFor: { one: 'Até {n} pessoa', other: 'Até {n} pessoas' },
    bathrooms: { one: '{n} banheiro', other: '{n} banheiros' },
    area: '{n} m²',
    levels: { one: 'Um piso', other: '{n} pisos' },
    beds: {
      doble: { one: '{n} cama de casal', other: '{n} camas de casal' },
      simple: { one: '{n} cama de solteiro', other: '{n} camas de solteiro' },
      triple: { one: '{n} cama tripla', other: '{n} camas triplas' },
      'sofa-cama': { one: '{n} sofá-cama', other: '{n} sofás-cama' },
    },
    labels: { guests: 'Capacidade', beds: 'Camas', bathrooms: 'Banheiros', area: 'Área', levels: 'Pisos' },
    whatsappMessage: 'Olá! Gostaria de consultar a disponibilidade da {name} no El Cadillar.',
    filterLabel: 'Filtrar cabanas por capacidade',
    filterAll: 'Todas',
    filterGuests: 'Até {n}',
  },
  gallery: {
    filterLabel: 'Filtrar fotos por espaço',
    open: 'Ampliar foto: {alt}',
  },
  lightbox: {
    label: 'Visualizador de fotos',
    counter: '{current} de {total}',
  },
  map: {
    title: 'Mapa com a localização do El Cadillar Apart Hotel',
    km: '{n} km',
  },
  mobileBar: {
    label: 'Reserva rápida',
    whatsapp: 'WhatsApp',
  },
  footer: {
    tagline: 'Natureza e descanso',
    explore: 'Explorar',
    contact: 'Contato',
    follow: 'Siga-nos',
    rights: '© {year} El Cadillar Apart Hotel. Todos os direitos reservados.',
    credit: 'Desenvolvido por',
    photoCredits: 'Fotos de Tarija: Wikimedia Commons, com licenças Creative Commons.',
  },
};
